### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by HummingMind** [nknapp/process-streams#4]
Hello,
Please upgrade the "tempfile" dependency from ^1.1.0 to the at least 4.0.0 or the latest 5.0.0 if possible.

"process-streams" relies on "tempfile", but older versions ofr "tempfile" are dependant on an older version of "uuid", which is buggy and is deprecated. Seems like "tempfile" dropped uuid as a dependancy in version 4.0.0.

So, the warning is not there with "tempfile" 4.0.0 (and 5.0.0)

Thank you!

Screenshot of the uuid dependency deprecation warning:

![image](https://github.com/Stieneee/simple-zstd/assets/87399963/eb788d58-41e9-451e-a930-58b38a22921b)

**Comment by nknapp** [comment]
Fixed in [version 1.0.3](https://github.com/nknapp/process-streams/blob/master/CHANGELOG.md#v103)
